---
apiVersion: v1
kind: Namespace
metadata:
  name: knot-dns
  labels:
    dns.gardener.cloud/allowed: "true"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: knot-dns
    app.kubernetes.io/name: knot-dns
  name: knot-dns
  namespace: knot-dns
spec:
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    app.kubernetes.io/instance: knot-dns
    app.kubernetes.io/name: knot-dns
  type: ClusterIP