---
apiVersion: extensions.gardener.cloud/v1alpha1
kind: Cluster
metadata:
  name: shoot--foo--bar
spec:
  cloudProfile:
    apiVersion: core.gardener.cloud/v1beta1
    kind: CloudProfile
  seed:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Seed
  shoot:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Shoot
    metadata:
      generation: 1
      name: shoot--foo--bar
    spec:
      dns:
        domain: foo.bar.example.com
      kubernetes:
        version: 1.28.2
    status:
      lastOperation:
        state: Succeeded
      observedGeneration: 1
      clusterIdentity: identity-shoot--foo--bar
