apiVersion: v1
kind: Service
metadata:
  annotations:
    dns.gardener.cloud/class: garden
    dns.gardener.cloud/dnsnames: dummy.xxx.ondemand.com
    # If you're using a load balancer on AWS and expect the creation of both `A` and `AAAA` records, uncomment the following line
    #dns.gardener.cloud/ip-stack: dual-stack
  name: dummy-service
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 1.2.3.4