apiVersion: testmachinery.sapcloud.io
kind: TestDefinition
metadata:
  name: shootdns-test
spec:
  owner: gardener-oq@listserv.sap.com
  description: System test for shoot DNS service

  activeDeadlineSeconds: 1800
  labels: ["shoot", "beta"]

  command: [bash, -c]
  args:
    - >-
      go test -timeout=0 ./test/system
      --v -ginkgo.v -ginkgo.progress -ginkgo.no-color
      -seed-kubecfg=$TM_KUBECONFIG_PATH/seed.config
      -shoot-kubecfg=$TM_KUBECONFIG_PATH/shoot.config
      -shoot-name=$SHOOT_NAME
      -project-namespace=$PROJECT_NAMESPACE
  image: golang:1.22.0
