apiVersion: testmachinery.sapcloud.io
kind: TestDefinition
metadata:
  name: shootdns-test
spec:
  owner: gardener-oq@listserv.sap.com
  description: System test for shoot DNS service

  activeDeadlineSeconds: 1800
  labels: ["shoot", "beta"]

  command: [bash, -c]
  args:
    - >-
      go test -timeout=0 ./test/system
      --v -ginkgo.v -ginkgo.progress -ginkgo.no-color
      --kubecfg="$TM_KUBECONFIG_PATH/gardener.config"
      --shoot-name=$SHOOT_NAME
      --existing-shoot-name=$SHOOT_NAME
      --project-namespace=$PROJECT_NAMESPACE
  image: golang:1.24.5
