global:
  virtualGarden:
    enabled: false
    user:
      name: ""
  image:
    repository: eu.gcr.io/gardener-project/gardener/extensions/admission-shoot-dns-service
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources: {}
  vpa:
    enabled: true
    resourcePolicy:
      minAllowed:
        memory: 64Mi
    updatePolicy:
      updateMode: "Auto"
  webhookConfig:
    serverPort: 10250
  # Kubeconfig to the target cluster. In-cluster configuration will be used if not specified.
  kubeconfig:

  serviceAccountTokenVolumeProjection:
    enabled: false
    expirationSeconds: 43200
    audience: ""
