apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: extension-shoot-dns-service
spec:
  deployment:
    extension:
      helm:
        ociRepository:
          ref: local-skaffold/gardener-extension-shoot-dns-service/charts/extension:v0.0.0
  resources:
  - kind: Extension
    type: shoot-dns-service
