apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: extension-shoot-dns-service
  annotations:
    security.gardener.cloud/pod-security-enforce: baseline

spec:
  deployment:
    admission:
      runtimeCluster:
        helm:
          ociRepository:
            ref: local-skaffold/gardener-extension-shoot-dns-service/charts/shoot-dns-service-admission-runtime:v0.0.0
      virtualCluster:
        helm:
          ociRepository:
            ref: local-skaffold/gardener-extension-shoot-dns-service/charts/shoot-dns-service-admission-application:v0.0.0