apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- extension.yaml

patches:
- path: extension-patch.yaml
- target:
    version: v1alpha1
    group: operator.gardener.cloud
    kind: Extension
    name: extension-shoot-dns-service
  patch: |
    - op: replace
      path: /spec/resources/0
      value:
        kind: Extension
        type: shoot-dns-service
        workerlessSupported: true
        autoEnable:
        - shoot
        clusterCompatibility:
        - shoot
