apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "name" . }}
  namespace: garden
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "name" . }}
  namespace: garden
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "name" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "name" . }}
  namespace: garden
