#!/usr/bin/env bash

set -e

"$(dirname $0)"/hack/set_dependency_version '{"external-dns-management": ["dns-controller-manager","dns-controller-manager-next-generation"]}'

# update copy in charts directory needed for installation after RBSC sync
cp "$(dirname $0)"/../imagevector/images.yaml "$(dirname $0)"/../charts/images.yaml

"$(dirname $0)"/../hack/.ci/set_dependency_version_dnsman

## need to update generated examples
make -C "$(dirname $0)"/.. generate