#!/usr/bin/env bash

set -e

"$(dirname $0)"/hack/set_dependency_version
# update copy in charts directory needed for installation after RBSC sync
cp "$(dirname $0)"/../imagevector/images.yaml "$(dirname $0)"/../charts/images.yaml

"$(dirname $0)"/../hack/.ci/set_dependency_version_dnsman

## need to update example/controller-registration.yaml
## as 'make generate' is not possible easily, we hav some duplicate steps here

# download helm
curl -sSfL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | HELM_INSTALL_DIR=/tmp USE_SUDO=false VERIFY_CHECKSUM=false bash -s -- --version v3.6.3
export PATH=/tmp:$PATH

# install gnutar
apk add tar yq

# generate example/controller-registration.yaml
cd "$(dirname $0)"/../charts/gardener-extension-shoot-dns-service
"$(dirname $0)"/hack/generate-controller-registration.sh extension-shoot-dns-service . $(cat ../../VERSION) ../../example/controller-registration.yaml Extension:shoot-dns-service
sed -i 's/ type: shoot-dns-service/ type: shoot-dns-service\n    workerlessSupported: true/' ../../example/controller-registration.yaml
