#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

repo_root="$(readlink -f $(dirname ${0})/..)"

echo "Generating ${repo_root}/dev/extension/kustomization.yaml"
mkdir -p ${repo_root}/dev/extension

cat  << EOF > ${repo_root}/dev/extension/kustomization.yaml
# DO NOT EDIT THIS FILE!
# This file is auto-generated by hack/prepare-dev-extension.sh.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../example/shoot-dns-service/base

patches:
- path: extension-patch.yaml
EOF

echo "Generating ${repo_root}/dev/extension/extension-patch.yaml"

cat  << EOF > ${repo_root}/dev/extension/extension-patch.yaml
# DO NOT EDIT THIS FILE!
# This file is auto-generated by hack/prepare-dev-extension.sh

apiVersion: operator.gardener.cloud/v1alpha1
kind: Extension
metadata:
  name: extension-shoot-dns-service
spec:
  deployment:
    admission:
      runtimeCluster:
        helm:
          ociRepository:
            ref: local-skaffold/gardener-extension-shoot-dns-service/charts/shoot-dns-service-admission-runtime:v0.0.0
      values:
        image:
          ref: local-skaffold/gardener-extension-admission-shoot-dns-service:v0.0.0
      virtualCluster:
        helm:
          ociRepository:
            ref: local-skaffold/gardener-extension-shoot-dns-service/charts/shoot-dns-service-admission-application:v0.0.0
    extension:
      values:
        image:
          ref: local-skaffold/gardener-extension-shoot-dns-service:v0.0.0
EOF