{{- if .Values.nextGeneration.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "service.name" . }}-next-generation-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config: |
{{- include "next-generation-config" . | indent 4 }}
{{- end }}