apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "service.name" . }}
    release: {{ .Release.Name }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "service.name" . }}
      release: {{ .Release.Name }}
{{- if semverCompare ">= 1.26-0" .Capabilities.KubeVersion.GitVersion }}
  unhealthyPodEvictionPolicy: AlwaysAllow
{{- end }}
