apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
