{{- if .Values.vpa.enabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: {{ template "service.name" . }}-vpa
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        controlledValues: RequestsOnly
        controlledResources: [memory]
        minAllowed:
          memory: {{ .Values.vpa.minAllowed.memory }}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "service.name" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode }}
{{- end }}