{
 "title": "Shoot DNS Service Dashboard",
 "tags": [
  "controlplane",
  "seed",
  "logging"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "UP Time",
   "type": "singlestat",
   "description": "Current uptime status.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(sum(up{job=\"shoot-dns-service\"} == 1) / sum(up{job=\"shoot-dns-service\"})) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "description": "Shows the CPU usage and shows the requests and limits.",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"shoot-dns-service-(.+)\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}-current"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\", pod=~\"shoot-dns-service-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", pod=~\"shoot-dns-service-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-requests"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Shows the memory usage.",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"shoot-dns-service-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-current"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\", pod=~\"shoot-dns-service-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-limits"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", pod=~\"shoot-dns-service-(.+)\"}) by (pod)",
     "legendFormat": "{{pod}}-requests"
    }
   ]
  },
  {
   "title": "DNS Entries",
   "type": "graph",
   "description": "The next-generation dns-controller-manager periodically lists all `DNSEntry` resources and aggregates them by hosted zone and reconciliation state. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(external_dns_management_dns_entries) by (providertype,zone,state)",
     "legendFormat": "{{providertype}}/{{zone}}/{{state}}"
    }
   ]
  },
  {
   "title": "Requests to DNS API Endpoints",
   "type": "graph",
   "description": "Cumulative number of API calls made to a DNS provider, broken down by provider type, zone, and request type",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(external_dns_management_requests_per_zone[$__rate_interval])) by (providertype,zone,requesttype)",
     "legendFormat": "{{providertype}}/{{zone}}/{{requesttype}}"
    }
   ]
  },
  {
   "title": "Lookup Processor Jobs",
   "type": "timeseries",
   "description": "The lookup processor resolves hostnames referenced in `DNSEntry` resources (targets using DNS names instead of IP addresses) and queues re-reconciliations when results change.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "external_dns_management_lookup_processor_jobs",
     "legendFormat": "jobs"
    }
   ]
  },
  {
   "title": "Lookups",
   "type": "graph",
   "description": "Lookups for all lookup jobs.\n\"skips\" is the rate  of hostname lookups skipped because the processor was overloaded.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "requests/s" }
   ],
   "targets": [
    {
     "expr": "rate(external_dns_management_lookup_processor_lookups[$__rate_interval])",
     "legendFormat": "lookups"
    },
    {
     "expr": "rate(external_dns_management_lookup_processor_skips[$__rate_interval])",
     "legendFormat": "skips"
    },
    {
     "expr": "rate(external_dns_management_lookup_processor_errors[$__rate_interval])",
     "legendFormat": "errors"
    },
    {
     "expr": "rate(external_dns_management_lookup_processor_lookup_changed[$__rate_interval])",
     "legendFormat": "changes"
    }
   ]
  },
  {
   "title": "Lookup Latency",
   "type": "heatmap",
   "description": "The lookup processor resolves hostnames referenced in `DNSEntry` resources (targets using DNS names instead of IP addresses) and queues re-reconciliations when results change.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(external_dns_management_lookup_processor_seconds_bucket[$__rate_interval])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{pod_name=~\"shoot-dns-service-(.+)\"} |~ \"$search\""
    }
   ]
  }
 ]
}