{{- if .Values.dnsControllerManager.configuration.serverPortHttp }}
apiVersion: v1
kind: Service
metadata:
  name: dns-controller-manager
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.resources.gardener.cloud/from-all-seed-scrape-targets-allowed-ports: '[{"port":{{ .Values.dnsControllerManager.configuration.serverPortHttp }},"protocol":"TCP"}]'
    networking.resources.gardener.cloud/namespace-selectors: '[{"matchLabels":{"kubernetes.io/metadata.name":"garden"}}]'
    networking.resources.gardener.cloud/pod-label-selector-namespace-alias: extensions
    # TODO: This label approach is deprecated and no longer needed in the future. Remove them as soon as gardener/gardener@v1.75 has been released.
    networking.resources.gardener.cloud/from-policy-pod-label-selector: all-seed-scrape-targets
    networking.resources.gardener.cloud/from-policy-allowed-ports: '[{"port":{{ .Values.dnsControllerManager.configuration.serverPortHttp }},"protocol":"TCP"}]'
  labels:
{{ include "dnsmanLabels" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: {{ .Values.dnsControllerManager.configuration.serverPortHttp }}
    protocol: TCP
  selector:
{{ include "dnsmanLabels" . | indent 4 }}
{{- end }}
