{{- if .Values.vpa.enabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: gardener-extension-shoot-dns-service-vpa
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          memory: {{ .Values.vpa.resourcePolicy.minAllowed.memory }}
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gardener-extension-shoot-dns-service
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode }}
{{- end }}