#!/usr/bin/env python3
#
# Copyright (c) 2023 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import pathlib

import ci.util

dependency_name = ci.util.check_env('DEPENDENCY_NAME')
dependency_version = ci.util.check_env('DEPENDENCY_VERSION')

values_file = pathlib.Path(
        ci.util.check_env('REPO_DIR'),
        'charts',
        'gardener-extension-shoot-dns-service',
        'values.yaml',
)
temp_file = values_file.parent.joinpath('~values.yaml.tmp~')

if dependency_name == 'external-dns-management':
  print(f'updating tag for dnsControllerManager to "{dependency_version}"')
  with open(temp_file, 'w') as fout:
    with open(values_file, 'r') as fin:
      for line in fin:
        if '# marker-for-image-tag-dns-controller-manager' in line:
          line = f'    tag: "{dependency_version}" # marker-for-image-tag-dns-controller-manager (please keep this comment for automated update by set_dependency_version_dnsman)\n'
        fout.write(line)

  temp_file.rename(values_file)