#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

import pathlib

import ci.util

dependency_name = ci.util.check_env('DEPENDENCY_NAME')
dependency_version = ci.util.check_env('DEPENDENCY_VERSION')

values_file = pathlib.Path(
        ci.util.check_env('REPO_DIR'),
        'charts',
        'gardener-extension-shoot-dns-service',
        'values.yaml',
)
temp_file = values_file.parent.joinpath('~values.yaml.tmp~')

if dependency_name == 'github.com/gardener/external-dns-management':
  print(f'updating tag for dnsControllerManager to "{dependency_version}"')
  with open(temp_file, 'w') as fout:
    with open(values_file, 'r') as fin:
      for line in fin:
        if '# marker-for-image-tag-dns-controller-manager' in line:
          line = f'    tag: "{dependency_version}" # marker-for-image-tag-dns-controller-manager (please keep this comment for automated update by set_dependency_version_dnsman)\n'
        fout.write(line)

  temp_file.rename(values_file)
